// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOiTlCEKt2UmJ_dbKTPEgfyj9aaBICQdg',
    appId: '1:232992044887:web:033bff99250d8cd0c5b012',
    messagingSenderId: '232992044887',
    projectId: 'tasks-2b9d4',
    authDomain: 'tasks-2b9d4.firebaseapp.com',
    storageBucket: 'tasks-2b9d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStFuZwPBC_Vk_YHiFZjzZ3ab2urGyEH4',
    appId: '1:232992044887:android:090b73a6ad427ba0c5b012',
    messagingSenderId: '232992044887',
    projectId: 'tasks-2b9d4',
    storageBucket: 'tasks-2b9d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt61OtIrgGVsKMseKYwGJgSQxAHin77m4',
    appId: '1:232992044887:ios:5aad6d20e0879f0fc5b012',
    messagingSenderId: '232992044887',
    projectId: 'tasks-2b9d4',
    storageBucket: 'tasks-2b9d4.appspot.com',
    iosClientId: '232992044887-kft8eu516rbmjhj42p42n3cbgrmpce51.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt61OtIrgGVsKMseKYwGJgSQxAHin77m4',
    appId: '1:232992044887:ios:5aad6d20e0879f0fc5b012',
    messagingSenderId: '232992044887',
    projectId: 'tasks-2b9d4',
    storageBucket: 'tasks-2b9d4.appspot.com',
    iosClientId: '232992044887-kft8eu516rbmjhj42p42n3cbgrmpce51.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagment',
  );
}
